SELECT 
  STORE_NBR AS CONTROL_STORE,
  ABS(SUM(TOT_SALES) - (SELECT SUM(TOT_SALES) 
                          FROM QVI_data 
                          WHERE STORE_NBR = 86)) AS DISTANCE
FROM QVI_data
WHERE STORE_NBR <> 86
GROUP BY STORE_NBR
ORDER BY DISTANCE ASC
LIMIT 3;
