WITH TrialMetrics AS (
    SELECT
        STORE_NBR AS TRIAL_STORE,
        SUM(TOT_SALES) AS TOTAL_SALES,
        COUNT(DISTINCT LYLTY_CARD_NBR) AS UNIQUE_CUSTOMERS,
        COUNT(DISTINCT TXN_ID) AS TOTAL_TRANSACTIONS,
        ROUND(COUNT(DISTINCT TXN_ID)/COUNT(DISTINCT LYLTY_CARD_NBR), 2) AS AVG_TXNS_PER_CUSTOMER
    FROM QVI_data
    WHERE STORE_NBR IN (77, 86, 88)
      AND DATE BETWEEN '2018-07-01' AND '2019-06-30'
    GROUP BY STORE_NBR
),

ControlMetrics AS (
    SELECT
        CASE 
            WHEN STORE_NBR IN (141, 46, 50) THEN 77
            WHEN STORE_NBR IN (155, 227, 236) THEN 86
            WHEN STORE_NBR IN (165, 40, 237) THEN 88
        END AS TRIAL_STORE,
        SUM(TOT_SALES) AS TOTAL_SALES
    FROM QVI_data
    WHERE STORE_NBR IN (141, 46, 50, 155, 227, 236, 165, 40, 237)
      AND DATE BETWEEN '2018-07-01' AND '2019-06-30'
    GROUP BY TRIAL_STORE, STORE_NBR
),

AvgControl AS (
    SELECT
        TRIAL_STORE,
        AVG(TOTAL_SALES) AS AVG_CONTROL_SALES
    FROM ControlMetrics
    GROUP BY TRIAL_STORE
)

SELECT
    t.TRIAL_STORE,
    t.TOTAL_SALES AS TRIAL_TOTAL_SALES,
    a.AVG_CONTROL_SALES,
    ROUND(((t.TOTAL_SALES - a.AVG_CONTROL_SALES)/a.AVG_CONTROL_SALES)*100, 2) AS SALES_UPLIFT_PERCENT,
    t.AVG_TXNS_PER_CUSTOMER
FROM TrialMetrics t
JOIN AvgControl a
ON t.TRIAL_STORE = a.TRIAL_STORE
ORDER BY t.TRIAL_STORE;
