SELECT
    STORE_NBR,
    'Trial' AS STORE_TYPE,
    SUM(TOT_SALES) AS TOTAL_SALES,
    COUNT(DISTINCT LYLTY_CARD_NBR) AS UNIQUE_CUSTOMERS,
    COUNT(DISTINCT TXN_ID) AS TOTAL_TRANSACTIONS,
    ROUND(COUNT(DISTINCT TXN_ID)/COUNT(DISTINCT LYLTY_CARD_NBR), 2) AS AVG_TXNS_PER_CUSTOMER
FROM QVI_data
WHERE STORE_NBR IN (77, 86, 88)
  AND DATE BETWEEN '2018-07-01' AND '2019-06-30'
GROUP BY STORE_NBR

UNION ALL

SELECT
    STORE_NBR,
    'Control' AS STORE_TYPE,
    SUM(TOT_SALES) AS TOTAL_SALES,
    COUNT(DISTINCT LYLTY_CARD_NBR) AS UNIQUE_CUSTOMERS,
    COUNT(DISTINCT TXN_ID) AS TOTAL_TRANSACTIONS,
    ROUND(COUNT(DISTINCT TXN_ID)/COUNT(DISTINCT LYLTY_CARD_NBR), 2) AS AVG_TXNS_PER_CUSTOMER
FROM QVI_data
WHERE STORE_NBR IN (141, 46, 50, 155, 227, 236, 165, 40, 237)
  AND DATE BETWEEN '2018-07-01' AND '2019-06-30'
GROUP BY STORE_NBR
ORDER BY STORE_NBR;
